#!/usr/bin/env bash
#
# Regenerate the photo gallery manifest.
# Run this after you add or remove images in the photos/ directory:
#
#     ./generate-gallery.sh
#
# It writes photos/manifest.js, which gallery.html reads to build the grid.
# The manifest is a plain .js file (not JSON) on purpose, so the gallery also
# works when you open gallery.html straight from disk (file://), no web server.

set -euo pipefail

# Always run relative to the repository root (where this script lives).
cd "$(dirname "$0")"

photos_dir="photos"
out="$photos_dir/manifest.js"

if [ ! -d "$photos_dir" ]; then
    echo "error: '$photos_dir' directory not found" >&2
    exit 1
fi

# Collect image files (case-insensitive extensions), sorted by name.
# The PXL_* filenames from Pixel phones sort chronologically, which is the
# order we want photos to appear in.
mapfile -t images < <(
    find "$photos_dir" -maxdepth 1 -type f \
        \( -iname '*.jpg'  -o -iname '*.jpeg' -o -iname '*.png' \
           -o -iname '*.webp' -o -iname '*.gif'  -o -iname '*.avif' \) \
        -printf '%f\n' | LC_ALL=C sort
)

{
    echo "// Auto-generated by generate-gallery.sh - do not edit by hand."
    echo "// Run ./generate-gallery.sh after adding or removing photos."
    echo "window.GALLERY_PHOTOS = ["
    for name in "${images[@]}"; do
        # Escape backslashes then double quotes for a safe JS string literal.
        esc=${name//\\/\\\\}
        esc=${esc//\"/\\\"}
        printf '  "%s",\n' "$esc"
    done
    echo "];"
} > "$out"

echo "Wrote $out (${#images[@]} photo(s))."
